name: Test-pipeline
on:
  push:
    branch:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  CI: false

jobs:
  echoing:
    runs-on: self-hosted
    steps:
      - run: echo "hello ${{ github.actor }} running on self hosted runner"
      - run: echo "Testing"
      - run: echo "success"

  build:
    needs: echoing
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo "Starting build process"
      - run: echo "Running on version"
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build
      - run: "mkdir artifact && mv build artifact/build"
      - name: set-artifact-name
        id: artifact-name
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Uploading Artifact
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'artifact/'
          destination: 'mew_artifacts/artifact_${{ steps.artifact-name.outputs.short_sha }}'

  deploy:
    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set-artifact-name
        id: artifact-name
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - run: "gcloud compute ssh --command 'whoami' mew-production-vm-instance-a-02 --zone us-central1-a"
      - run: "gcloud compute ssh --command 'sudo systemctl stop start-next-server.service' mew-production-vm-instance-a-02 --zone us-central1-a"
      - run: "gcloud compute ssh --command 'gsutil cp -r gs://mew_artifacts/artifact_${{ steps.artifact-name.outputs.short_sha }}/artifact /home/gagan' mew-production-vm-instance-a-02 --zone us-central1-a"
      - run: "gcloud compute ssh --command 'sudo systemctl start start-next-server.service' mew-production-vm-instance-a-02 --zone us-central1-a"


