name: Test-pipeline
on:
  push:
    branch:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: mew-production-vm-group-xhgg
  GCE_INSTANCE_ZONE: asia-south1-a

jobs:
  echoing:
    runs-on: self-hosted
    steps:
      - run: echo "hello ${{ github.actor }} running on self hosted runner"
      - run: echo "Testing"
      - run: echo "success"

  deploy:
    needs: echoing
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - run: "gcloud compute ssh --command 'sudo systemctl stop ${{ secrets.START_APP }}' mew-production-vm-group-xhgg --zone asia-south1-a"
      - run: "gcloud compute ssh --command 'rm -rf ModernEraWeb' mew-production-vm-group-xhgg --zone asia-south1-a"
      - run: "gcloud compute ssh --command 'git clone git@github.com:gagansingh3785/ModernEraWeb.git && sudo systemctl start ${{ secrets.START_APP }}' mew-production-vm-group-xhgg --zone asia-south1-a"


