name: Test-pipeline
on:
  push:
    branch:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: mew-production-vm-group-xhgg
  GCE_INSTANCE_ZONE: asia-south1-a

jobs:
  echoing:
    runs-on: self-hosted
    steps:
      - run: echo "hello ${{ github.actor }} running on self hosted runner"
      - run: echo "Testing"
      - run: echo "success"

  build:
    needs: echoing
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_STORAGE_SERVICE_ACCOUNT_KEY }}'

      - run: echo "Starting build process"
      - run: echo "Running on version"
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run build
      - run: "mkdir artifact && mv package.json artifact/package.json && mv package-lock.json artifact/package-lock.json && mv .next artifact/.next
      && mv next.config.js artifact/next.config.js"
      - name: set-artifact-name
        id: artifact-name
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Uploading Artifact
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: 'artifact/'
          destination: 'mew_artifacts/artifact_${{ steps.artifact-name.outputs.short_sha }}'

  deploy:
    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: set-artifact-name
        id: artifact-name
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - run: "gcloud compute ssh --command 'curl http://storage.googleapis.com/mew_artifacts/artifact_${{ steps.artifact-name.outputs.short_sha }}/ && cd artifact_${{ steps.artifact-name.outputs.short_sha }}' mew-production-vm-group-xhgg --zone asia-south1-a"


